version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: timesheet_sql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: timesheet
      MYSQL_USER: wesley
      MYSQL_PASSWORD: wesley
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
